### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by arendina** [laravel-italia/site#10]
In questa pagina:
http://laravel-italia.it/articoli/creare-un-blog-con-laravel-5/parte-2-preparare-lambiente-di-lavoro
C'è questa riga che punta a un dead-link:
<a target="_blank" href="http://laravel-italia.it/articoli/video-alla-scoperta-di-homestead-improved">come installarlo in questo Articolo</a>

**Comment by ChristianGiupponi** [comment]
Credo sia stato risolto, puoi controllare?

**Comment by arendina** [comment]
Ho controllato. Funziona!

Il 13/07/2016 09:48, Christian Giupponi ha scritto:
