### ISSUE TITLE
Primo articolo errato sulle serie "Design Pattern e Laravel" e "Creare un Blog con Laravel 5"

### ISSUE THREAD

**Issue by afrittella** [laravel-italia/site#3]
Cliccando sulla serie [Design Pattern e Laravel](http://laravel-italia.it/serie/design-pattern-e-laravel), il metodo _getSeriesFirstArticle_ di _FrontController_ redirige all'articolo con lo slug [introduzione](http://laravel-italia.it/articoli/introduzione) che invece fa parte della serie [Making of Larabox](http://laravel-italia.it/serie/making-of-larabox) 

Allo stesso modo, il primo articolo di [Creare un Blog con Laravel 5](http://laravel-italia.it/serie/creare-un-blog-con-laravel-5) è quello di [Laravel in profondità](http://laravel-italia.it/serie/laravel-in-profondita), con slug [parte-1-introduzione](http://laravel-italia.it/articoli/parte-1-introduzione).

**Comment by francescomalatesta** [comment]
Sistemato!

Ref. [https://github.com/laravel-italia/site/commit/ce6ba86306d1e21f94c8797a9cc08b9cfeb79fa5](https://github.com/laravel-italia/site/commit/ce6ba86306d1e21f94c8797a9cc08b9cfeb79fa5)

Ref2. [https://github.com/laravel-italia/site/commit/30c472b70956852bafc867ea00d7fc745c0d050b](https://github.com/laravel-italia/site/commit/30c472b70956852bafc867ea00d7fc745c0d050b)
