### ISSUE TITLE
Testi troncati su mobile

### ISSUE THREAD

**Issue by ghost** [laravel-italia/site#6]
Alcuni testi sono troncati su mobile, riproducibile con Chrome 51 e Android.

**Comment by francescomalatesta** [comment]
Grazie per la segnalazione :) di che testi parli? Altrimenti non ho elementi...

**Comment by ghost** [comment]
Oh scusa in effetti non mi sono spiegato bene, 
I testi sono: - Vuoi saperne di più? 
- Serve una mano?

**Comment by francescomalatesta** [comment]
Link sistemati in [https://github.com/laravel-italia/site/commit/9e394b3b085cea9a8ebd83ba65a1aecc1bc10a19](https://github.com/laravel-italia/site/commit/9e394b3b085cea9a8ebd83ba65a1aecc1bc10a19)... closing :) grazie per la segnalazione
