### ISSUE TITLE
Pagina 404

### ISSUE THREAD

**Issue by m33ch** [laravel-italia/site#8]
Ciao ragazzi,

segnalo che la pagina 404 è quella di default di Laravel.
Sarebbe carino averne una con lo stesso stile del sito :)

**Comment by francescomalatesta** [comment]
Bella idea! Risolto in [https://github.com/laravel-italia/site/commit/d0a9c50494189ab89b4ac6347bef66fab07311f7](https://github.com/laravel-italia/site/commit/d0a9c50494189ab89b4ac6347bef66fab07311f7).
