### ISSUE TITLE
Paginazione errata articoli per categoria

### ISSUE THREAD

**Issue by afrittella** [laravel-italia/site#9]
Se scelgo una categoria nella sezione Articoli (ad es. [Tutorial](http://laravel-italia.it/articoli?categoria=tutorial)), i link della paginazione sono errati.

Il link della pagina 2 dovrebbe essere: http://laravel-italia.it/articoli?categoria=tutorial&page=2

Invece è: http://laravel-italia.it/articoli?0=categoria&page=2

Credo che l'errore sia nel file https://github.com/laravel-italia/site/blob/master/resources/views/front/articles.blade.php alla riga 76

`{!! $articles->appends(['categoria'])->render() !!}`

che secondo me dovrebbe essere:

`{!! $articles->appends(['categoria' => $category->slug])->render() !!}`

ma solo se presente la categoria.

**Comment by francescomalatesta** [comment]
Sistemato con [https://github.com/laravel-italia/site/commit/a99fc47b6b32717f34cceeea2b1f5e601fe7d59d](https://github.com/laravel-italia/site/commit/a99fc47b6b32717f34cceeea2b1f5e601fe7d59d). Chiudo.
